FROM node:16-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Copy app files
COPY . ./
# Cache and Install dependencies
RUN npm install 
RUN npm install  
RUN npm install express --save
RUN npm install mysql --save
RUN npm install body-parser --save
RUN npm i nodemon --save-dev
# Copy app files
# Expose port
EXPOSE 3000
# Start the app
CMD ["nodemon", "start"]