version: "3.8"
services:
  app:
    container_name: Backup-BE
    image: be_0810
    restart: always
    build:
      context: .
      target: backend
    volumes:
      - ./:/app
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_backup
    ports:
        - 3307:3306
    restart: always
    volumes:
        - /home/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER : test
      MYSQL_PASSWORD : P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
