version: "3.8"
services:
  app:
    container_name: Backup-FE
    image: fe_0810
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
